### ISSUE TITLE
STSANet.py details

### ISSUE THREAD

**Issue by Yangziyu** [come880412/STSANet#1]
Thank you for your sharing! It's a really excellent work, but I have some question when I run the STSANet.py, the dimension of the input image  is (*, *, * , 224, 384), it doesn't match the expected dimension of the spatial_bottleneck (* , * , * , 48, 28), it seems that the h and w dimensions are reversed. I switched the dimensions of h and w dimension of the input, but it caused a number of problems. 

blow is the logs:
Given normalized_shape=[192, 4, 48, 28], expected input with shape [*, 192, 4, 48, 28], but got input of size[3, 192, 4, 28, 48]
Train[0/250]:   0% 0/199 [00:10<?, ? step/s]

**Comment by come880412** [comment]
Hi,

Thanks for your feedback.
I found that the dimension of the comment is wrong, I have fixed it!
The input image is (B, 3, T, 224, 384), where width and height are respectively 224 and 384

Hope this helps!

**Comment by Yangziyu** [comment]
已收到你的邮件。

**Comment by Yangziyu** [comment]
Thanks for your reply.
I have changed the width to 224 and height to 384 in STSANet.py and run_train.sh. It works now. Thanks a lot!
